### ISSUE TITLE
Uses runtime-only build of Vue, even though webpack-simple uses the full version by default

### ISSUE THREAD

**Issue by jnvsor** [vuejs-templates/browserify-simple#17]
I'm not complaining that the built file from browserify-simple is 27kb (~33%) lighter than the one from webpack-simple, but since most of that is vital vue functionality it's a bit counterproductive!

## Reproduce

```bash
vue init browserify-simple vue
cd vue
npm i
npm run build
```

==> src/App.js <==

```js
import Vue from 'vue'
import App from './App.vue'

Vue.component('my-comp', App);
console.log(App);
debugger;

export default {
    v: Vue,
}
```

==> src/main.js <==

```js
import App from './App.js'

if (true) {
    window.test = App;
}
```

==> index.html <==

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>vue</title>
  </head>
  <body>
    <div id="wrap"><my-comp></my-comp></div>
    <script src="dist/build.js"></script>
    <script>
    new window.test.v({el:'#wrap'});
    </script>
  </body>
</html>
```

The resulting dist/build.js is 59kb, and you get WSOD. Doing the exact same with `webpack-simple` instead results in an 86kb file and the typical vue demo app

**Comment by chrisvfritz** [comment]
It's not actually vital Vue functionality - the lighter runtime build simply prevents the use of templates outside of `.vue` files. From [the docs](https://vuejs.org/v2/guide/installation.html#Terms): 

> CommonJS builds are intended for use with older bundlers like browserify or webpack 1. The default file for these bundlers (pkg.main) is the Runtime only CommonJS build (vue.runtime.common.js).

You can find more information and instructions on how to use the full version of Vue that includes the compiler [here](https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only).

However - since both `browserify-simple` and `webpack-simple` are meant for quick prototyping, rather than optimized production apps, I do think it makes sense to make both default to the full version. 👍  Will discuss with the rest of the team and update soon if others agree.

**Comment by jnvsor** [comment]
Ah, thanks for clarifying. (And for the docs link)
